project:
  type: book
  output-dir: docs

execute:
  echo: true

book:
  title: "Crowdfunding Analysis Project"
  author:
    - Yilan Chen (yc4355)
    - Orianne Luo (ol2216)
  repo-url: https://github.com/1819398633/crowd_funding.git
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - d3graph.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


