# Conclusion

Our analysis gave us insights about the types of projects that are on Kickstarter. In particular, we found that the most common categories for the projects in our dataset were Film & Video, Music, and Publishing. This indicates that most of the projects tend to be creative in nature, as well as artistic and digital. Moreover, we could see that most of the projects were located in the United States, though there were also many located in Europe and dispersed across the other continents. 

By comparing the projects that were successful to the projects that failed, we were also able to identify some patterns. For instance, whether or not the project was Facebook connected did not have much of an effect on whether or not it was successful. However, projects that were successful tended to have videos included with them, as well as more Facebook shares and more updates. Moreover, the categories with the highest proportion of successful projects were Dance, Theater, and Music. While Music was one of the most common categories for projects, Dance and Theater were some of the least common categories. This suggests that there may be a difference in the project creators’ interests compared to the project backers’ interests. We also found that the correlation between the amount pledged and the goal for the successful projects was close to 1 for successful projects. The amount pledged usually does not drastically exceed the project goal, which indicates that the behavior of the backers is influenced by the goal of the projects.

Some of the limitations we faced in our analysis came from the dataset itself, as it only contains a subset of the vast number of projects on the Kickstarter website. The project start dates only range from December 2013 to June 2014. To get a more comprehensive view of all the projects on Kickstarter, we may want to instead randomly sample from all of the projects on Kickstarter, from when the website was launched until the present day. Moreover, the dataset was a stratified sample of the Kickstarter projects, with a roughly equal number of successful and failed projects. To get a more accurate picture of the proportion of successful and failed projects on Kickstarter overall, we may want to take a random sample instead of a random stratified sample. Finally, the dataset is focused on the creators of the projects, with no little information about the backers of the projects. Going forward, because the behaviors of the backers plays an important role in the success of a project, we may also want to collect data on the characteristics of project backers on Kickstarter. 

Some of the lessons we learned were that some data visualizations, such as parallel coordinate plots and interactive scatterplots, can be unwieldy if we are dealing with very large datasets. We utilized them for gaining insights on a smaller sample of the data, though sometimes, the insights did not generalize to the larger datasets. Thus, there is always the need for verification using the entire dataset. 
