# Introduction
 
In recent years, crowdfunding has become very prevalent, especially for aspiring entrepreneurs who are hoping to raise money for their projects. Crowdfunding allows people and organizations to raise money for their projects, while also allowing donors to support the causes that they believe in. There have been many successful crowdfunding projects over the years, created by both creative artists and companies. There are two main types of crowdfunding projects, rewards crowdfunding and equity crowdfunding. Rewards crowdfunding is described as a way for entrepreneurs to pre-sell a product or service, while equity crowdfunding is a way for the supporters to purchase unlisted shares of a company. The rise of social media has also made it easier to share crowdfunding projects, drawing the attention of people from around the world to support the project. 
 
Kickstarter is one of the largest and most notable crowdfunding platforms. It is a website where individuals and organizations can post their projects, and backers can pledge money to projects that interest them. If the project is successful, then the pledge will go through; otherwise, the money is returned to the backers. Some crowdfunding projects on Kickstarter were very successful; for example, Coolest Cooler raised over $13 million to create a cooler, while artists such as Amanda Palmer and Zach Braff were able to raise $1.2 million and $3 million, respectively, for their creative endeavors. However, many crowdfunding projects fail to meet their target amount. 
 
We are interested in exploring the different types of crowdfunding projects, specifically on Kickstarter. Where are the project creators located, and what types of projects are more common? We would also like to see if some projects are more likely to succeed than other projects, based on the characteristics of those projects, project pages, and the creators of the projects. What is the distribution of the target amount of donations that the projects hope to raise, and what is the distribution of the amount that is actually pledged? We could also explore the effects of social media on the success of the projects. We would also like to gain insight on the behaviors of project backers, specifically to see if this behavior differs for projects that were successful versus projects that were unsuccessful. 

Sources: https://www.entrepreneur.com/starting-a-business/crowdfunding-generates-more-than-60000-an-hour/234051
https://www.theguardian.com/technology/2014/apr/17/kickstarter-crowdfunding-technology-film-games
